/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BKBusinessPlanPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/planView.ts
var import_obsidian = require("obsidian");

// src/planData.ts
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substr(2);
}
function createNewPlan(name, template = "blank") {
  const baseplan = {
    id: generateId(),
    name,
    description: "",
    icon: "\u{1F4CA}",
    color: "#3498db",
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    executive: {
      businessName: name,
      tagline: "",
      mission: "",
      vision: "",
      coreValues: [],
      targetMarket: "",
      uniqueValue: "",
      foundedDate: "",
      founder: ""
    },
    products: [],
    bundles: [],
    market: {
      marketSize: "",
      growthRate: "",
      trends: [],
      targetSegments: [],
      competitors: [],
      differentiators: [],
      opportunities: [],
      threats: []
    },
    marketing: {
      websiteUrl: "",
      channels: [],
      funnel: {
        awareness: [],
        interest: [],
        consideration: [],
        conversion: [],
        retention: []
      },
      pricingStrategy: "",
      promotions: [],
      partnerships: []
    },
    operations: {
      developmentProcess: "",
      releaseSchedule: "",
      supportChannels: [],
      distributionMethod: "",
      processes: [],
      tools: []
    },
    technology: {
      stack: [],
      licensingSystem: "",
      paymentProcessors: [],
      analyticsTools: []
    },
    financial: {
      revenueStreams: [],
      expenses: [],
      projections: [],
      startupCosts: 0,
      breakEvenPoint: "",
      fundingNeeds: ""
    },
    legal: {
      businessStructure: "",
      licensingModel: "",
      documents: [],
      complianceNotes: []
    },
    roadmap: {
      milestones: [],
      quarterlyGoals: {},
      longTermVision: ""
    }
  };
  if (template === "plugin-business") {
    baseplan.icon = "\u{1F50C}";
    baseplan.color = "#9b59b6";
    baseplan.executive.mission = "Empower users with powerful, easy-to-use plugins.";
    baseplan.executive.coreValues = ["User-First Design", "Quality & Reliability", "Continuous Improvement"];
    baseplan.market.targetSegments = ["Small Businesses", "Productivity Enthusiasts", "Knowledge Workers"];
    baseplan.market.differentiators = ["Superior documentation", "Regular updates", "Excellent support"];
    baseplan.marketing.funnel = {
      awareness: ["Content marketing", "Plugin directories", "Social media"],
      interest: ["Free trial/lite versions", "Documentation", "Demo videos"],
      consideration: ["Comparison guides", "Testimonials", "Feature highlights"],
      conversion: ["Promotional discounts", "Bundle deals"],
      retention: ["Email updates", "New features", "Community engagement"]
    };
    baseplan.legal.licensingModel = "GPL for PHP, commercial EULA for JS/assets";
    baseplan.technology.paymentProcessors = ["Stripe", "PayPal"];
  } else if (template === "saas") {
    baseplan.icon = "\u2601\uFE0F";
    baseplan.color = "#3498db";
    baseplan.market.targetSegments = ["SMBs", "Enterprise", "Startups"];
    baseplan.marketing.funnel = {
      awareness: ["SEO", "Content marketing", "Paid ads"],
      interest: ["Free trial", "Webinars", "Case studies"],
      consideration: ["Demo calls", "ROI calculator", "Comparisons"],
      conversion: ["Annual discount", "Onboarding support"],
      retention: ["Customer success", "Feature updates", "Community"]
    };
  } else if (template === "consulting") {
    baseplan.icon = "\u{1F4BC}";
    baseplan.color = "#27ae60";
    baseplan.market.targetSegments = ["Businesses needing expertise", "Project-based clients"];
    baseplan.marketing.funnel = {
      awareness: ["Networking", "Referrals", "LinkedIn"],
      interest: ["Portfolio", "Case studies", "Blog"],
      consideration: ["Discovery calls", "Proposals"],
      conversion: ["Contract signing"],
      retention: ["Ongoing retainers", "Follow-up projects"]
    };
  } else if (template === "nonprofit") {
    baseplan.icon = "\u2764\uFE0F";
    baseplan.color = "#e74c3c";
    baseplan.executive.coreValues = ["Community Impact", "Transparency", "Sustainability"];
    baseplan.market.targetSegments = ["Donors", "Volunteers", "Beneficiaries"];
  }
  return baseplan;
}
function formatCurrency(amount) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD"
  }).format(amount);
}
function formatDate(date) {
  if (!date)
    return "";
  return new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric"
  });
}
function calculateMonthlyRevenue(streams) {
  return streams.reduce((sum, s) => sum + s.monthlyEstimate, 0);
}
function getProductsByStatus(products, status) {
  return products.filter((p) => p.status === status);
}
function getMilestonesByStatus(milestones, status) {
  return milestones.filter((m) => m.status === status);
}

// src/planView.ts
var VIEW_TYPE_BUSINESS_PLAN = "bk-business-plan-view";
var BusinessPlanView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeSection = "plans";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_BUSINESS_PLAN;
  }
  getDisplayText() {
    return "Business Plan";
  }
  getIcon() {
    return "briefcase";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  refresh() {
    this.render();
  }
  getActivePlan() {
    return this.plugin.getActivePlan();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bk-plan-container");
    this.renderHeader(contentEl);
    if (this.plugin.settings.plans.length === 0) {
      this.renderNoPlanView(contentEl);
      return;
    }
    this.renderNavigation(contentEl);
    const mainContent = contentEl.createDiv({ cls: "bk-plan-content" });
    switch (this.activeSection) {
      case "plans":
        this.renderPlanManager(mainContent);
        break;
      case "dashboard":
        this.renderDashboard(mainContent);
        break;
      case "executive":
        this.renderExecutive(mainContent);
        break;
      case "products":
        this.renderProducts(mainContent);
        break;
      case "market":
        this.renderMarket(mainContent);
        break;
      case "marketing":
        this.renderMarketing(mainContent);
        break;
      case "operations":
        this.renderOperations(mainContent);
        break;
      case "technology":
        this.renderTechnology(mainContent);
        break;
      case "financial":
        this.renderFinancial(mainContent);
        break;
      case "legal":
        this.renderLegal(mainContent);
        break;
      case "roadmap":
        this.renderRoadmap(mainContent);
        break;
    }
  }
  // =========================================
  // HEADER WITH PLAN SELECTOR
  // =========================================
  renderHeader(container) {
    const header = container.createDiv({ cls: "bk-plan-header" });
    const titleRow = header.createDiv({ cls: "bk-plan-title-row" });
    titleRow.createEl("h1", { text: "\u{1F4CA} Business Plan Manager" });
    if (this.plugin.settings.plans.length > 0) {
      const planSelector = titleRow.createDiv({ cls: "bk-plan-selector" });
      const selectEl = planSelector.createEl("select", { cls: "bk-plan-dropdown" });
      this.plugin.settings.plans.forEach((plan) => {
        const option = selectEl.createEl("option", {
          text: `${plan.icon} ${plan.name}`,
          value: plan.id
        });
        if (plan.id === this.plugin.settings.activePlanId) {
          option.selected = true;
        }
      });
      selectEl.addEventListener("change", async (e) => {
        const newId = e.target.value;
        this.plugin.settings.activePlanId = newId;
        await this.plugin.saveSettings();
        this.refresh();
        const plan = this.getActivePlan();
        if (plan) {
          new import_obsidian.Notice(`Switched to "${plan.name}"`);
        }
      });
      const newPlanBtn = planSelector.createEl("button", {
        text: "+ New",
        cls: "bk-new-plan-btn"
      });
      newPlanBtn.addEventListener("click", () => {
        new QuickCreatePlanModal(this.app, this.plugin, () => {
          this.refresh();
        }).open();
      });
    }
    header.createEl("p", {
      text: "Plan, track, and grow your business",
      cls: "bk-plan-subtitle"
    });
  }
  // =========================================
  // NO PLAN VIEW
  // =========================================
  renderNoPlanView(container) {
    const emptyState = container.createDiv({ cls: "bk-empty-state" });
    emptyState.createEl("div", { text: "\u{1F4CB}", cls: "bk-empty-icon" });
    emptyState.createEl("h2", { text: "No Business Plans Yet" });
    emptyState.createEl("p", { text: "Create your first business plan to get started." });
    const templateGrid = emptyState.createDiv({ cls: "bk-template-grid" });
    const templates = [
      { id: "blank", icon: "\u{1F4C4}", name: "Blank Plan", desc: "Start from scratch" },
      { id: "plugin-business", icon: "\u{1F50C}", name: "Plugin Business", desc: "WordPress/Obsidian plugins" },
      { id: "saas", icon: "\u2601\uFE0F", name: "SaaS Business", desc: "Software as a Service" },
      { id: "consulting", icon: "\u{1F4BC}", name: "Consulting", desc: "Professional services" },
      { id: "nonprofit", icon: "\u2764\uFE0F", name: "Non-profit", desc: "Mission-driven organization" }
    ];
    templates.forEach((template) => {
      const card = templateGrid.createDiv({ cls: "bk-template-card" });
      card.createEl("div", { text: template.icon, cls: "template-icon" });
      card.createEl("div", { text: template.name, cls: "template-name" });
      card.createEl("div", { text: template.desc, cls: "template-desc" });
      card.addEventListener("click", async () => {
        const name = await this.promptPlanName(template.name);
        if (name) {
          const newPlan = createNewPlan(name, template.id);
          this.plugin.settings.plans.push(newPlan);
          this.plugin.settings.activePlanId = newPlan.id;
          await this.plugin.saveSettings();
          this.activeSection = "dashboard";
          this.refresh();
          new import_obsidian.Notice(`Created "${name}"!`);
        }
      });
    });
  }
  async promptPlanName(defaultName) {
    return new Promise((resolve) => {
      const modal = new import_obsidian.Modal(this.app);
      let inputValue = defaultName;
      modal.contentEl.createEl("h3", { text: "\u{1F4DD} Name Your Business Plan" });
      const inputEl = modal.contentEl.createEl("input", {
        type: "text",
        value: defaultName,
        cls: "bk-plan-name-input"
      });
      inputEl.style.width = "100%";
      inputEl.style.padding = "8px";
      inputEl.style.marginBottom = "16px";
      inputEl.addEventListener("input", (e) => {
        inputValue = e.target.value;
      });
      const btnRow = modal.contentEl.createDiv({ cls: "bk-modal-buttons" });
      const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
      cancelBtn.addEventListener("click", () => {
        modal.close();
        resolve(null);
      });
      const createBtn = btnRow.createEl("button", { text: "Create", cls: "mod-cta" });
      createBtn.addEventListener("click", () => {
        modal.close();
        resolve(inputValue.trim() || defaultName);
      });
      modal.open();
      inputEl.focus();
      inputEl.select();
    });
  }
  // =========================================
  // NAVIGATION
  // =========================================
  renderNavigation(container) {
    const nav = container.createDiv({ cls: "bk-plan-nav" });
    const sections = [
      { id: "plans", icon: "\u{1F4CB}", label: "Plans" },
      { id: "dashboard", icon: "\u{1F4CA}", label: "Dashboard" },
      { id: "executive", icon: "\u{1F3AF}", label: "Executive" },
      { id: "products", icon: "\u{1F4E6}", label: "Products" },
      { id: "market", icon: "\u{1F4C8}", label: "Market" },
      { id: "marketing", icon: "\u{1F4E3}", label: "Marketing" },
      { id: "operations", icon: "\u2699\uFE0F", label: "Operations" },
      { id: "technology", icon: "\u{1F4BB}", label: "Technology" },
      { id: "financial", icon: "\u{1F4B0}", label: "Financial" },
      { id: "legal", icon: "\u{1F4DC}", label: "Legal" },
      { id: "roadmap", icon: "\u{1F5FA}\uFE0F", label: "Roadmap" }
    ];
    sections.forEach((section) => {
      const btn = nav.createEl("button", {
        cls: `bk-nav-btn ${this.activeSection === section.id ? "active" : ""}`
      });
      btn.createEl("span", { text: section.icon, cls: "nav-icon" });
      btn.createEl("span", { text: section.label, cls: "nav-label" });
      btn.addEventListener("click", () => {
        this.activeSection = section.id;
        this.refresh();
      });
    });
  }
  // =========================================
  // PLAN MANAGER
  // =========================================
  renderPlanManager(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4CB} Manage Business Plans" });
    const plans = this.plugin.settings.plans;
    const createCard = section.createDiv({ cls: "bk-create-plan-card" });
    createCard.createEl("span", { text: "+", cls: "create-icon" });
    createCard.createEl("span", { text: "Create New Plan", cls: "create-text" });
    createCard.addEventListener("click", () => {
      new QuickCreatePlanModal(this.app, this.plugin, () => {
        this.refresh();
      }).open();
    });
    const planGrid = section.createDiv({ cls: "bk-plans-grid" });
    plans.forEach((plan) => {
      const card = planGrid.createDiv({ cls: "bk-plan-card" });
      if (plan.id === this.plugin.settings.activePlanId) {
        card.addClass("is-active");
      }
      card.style.borderColor = plan.color;
      const cardHeader = card.createDiv({ cls: "plan-card-header" });
      cardHeader.createEl("span", { text: plan.icon, cls: "plan-card-icon" });
      cardHeader.createEl("span", { text: plan.name, cls: "plan-card-name" });
      if (plan.id === this.plugin.settings.activePlanId) {
        cardHeader.createEl("span", { text: "\u2713", cls: "plan-card-active" });
      }
      const cardInfo = card.createDiv({ cls: "plan-card-info" });
      if (plan.description) {
        cardInfo.createEl("p", { text: plan.description, cls: "plan-card-desc" });
      }
      const statsRow = cardInfo.createDiv({ cls: "plan-card-stats" });
      statsRow.createEl("span", { text: `\u{1F4E6} ${plan.products.length} products` });
      statsRow.createEl("span", { text: `\u{1F3AF} ${plan.roadmap.milestones.length} milestones` });
      cardInfo.createEl("span", {
        text: `Updated: ${formatDate(plan.lastUpdated)}`,
        cls: "plan-card-date"
      });
      const cardActions = card.createDiv({ cls: "plan-card-actions" });
      if (plan.id !== this.plugin.settings.activePlanId) {
        const activateBtn = cardActions.createEl("button", { text: "Activate", cls: "mod-cta" });
        activateBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          this.plugin.settings.activePlanId = plan.id;
          await this.plugin.saveSettings();
          this.activeSection = "dashboard";
          this.refresh();
          new import_obsidian.Notice(`Activated "${plan.name}"`);
        });
      } else {
        const viewBtn = cardActions.createEl("button", { text: "View Dashboard", cls: "mod-cta" });
        viewBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.activeSection = "dashboard";
          this.refresh();
        });
      }
      const deleteBtn = cardActions.createEl("button", { text: "\u{1F5D1}\uFE0F", cls: "plan-delete-btn" });
      deleteBtn.addEventListener("click", async (e) => {
        var _a;
        e.stopPropagation();
        if (confirm(`Delete "${plan.name}"? This cannot be undone.`)) {
          this.plugin.settings.plans = this.plugin.settings.plans.filter((p) => p.id !== plan.id);
          if (this.plugin.settings.activePlanId === plan.id) {
            this.plugin.settings.activePlanId = ((_a = this.plugin.settings.plans[0]) == null ? void 0 : _a.id) || "";
          }
          await this.plugin.saveSettings();
          this.refresh();
          new import_obsidian.Notice(`Deleted "${plan.name}"`);
        }
      });
    });
  }
  // =========================================
  // DASHBOARD
  // =========================================
  renderDashboard(container) {
    const plan = this.getActivePlan();
    if (!plan) {
      container.createEl("p", { text: "No plan selected", cls: "bk-no-plan" });
      return;
    }
    const welcome = container.createDiv({ cls: "bk-section bk-welcome-section" });
    welcome.createEl("h2", { text: `${plan.icon} ${plan.executive.businessName || plan.name}` });
    if (plan.executive.mission) {
      welcome.createEl("p", { text: plan.executive.mission, cls: "bk-mission-text" });
    }
    const statsGrid = container.createDiv({ cls: "bk-stats-grid" });
    const productsStat = statsGrid.createDiv({ cls: "bk-stat-card" });
    productsStat.createEl("span", { text: "\u{1F4E6}", cls: "stat-icon" });
    productsStat.createEl("span", { text: plan.products.length.toString(), cls: "stat-value" });
    productsStat.createEl("span", { text: "Products", cls: "stat-label" });
    const launchedStat = statsGrid.createDiv({ cls: "bk-stat-card" });
    launchedStat.createEl("span", { text: "\u{1F680}", cls: "stat-icon" });
    const launched = getProductsByStatus(plan.products, "launched").length;
    launchedStat.createEl("span", { text: launched.toString(), cls: "stat-value" });
    launchedStat.createEl("span", { text: "Launched", cls: "stat-label" });
    const revenueStat = statsGrid.createDiv({ cls: "bk-stat-card" });
    revenueStat.createEl("span", { text: "\u{1F4B0}", cls: "stat-icon" });
    const monthlyRev = calculateMonthlyRevenue(plan.financial.revenueStreams);
    revenueStat.createEl("span", { text: formatCurrency(monthlyRev), cls: "stat-value" });
    revenueStat.createEl("span", { text: "Est. Monthly", cls: "stat-label" });
    const milestonesStat = statsGrid.createDiv({ cls: "bk-stat-card" });
    milestonesStat.createEl("span", { text: "\u{1F3AF}", cls: "stat-icon" });
    const completed = getMilestonesByStatus(plan.roadmap.milestones, "completed").length;
    const total = plan.roadmap.milestones.length;
    milestonesStat.createEl("span", { text: `${completed}/${total}`, cls: "stat-value" });
    milestonesStat.createEl("span", { text: "Milestones", cls: "stat-label" });
    const actionsSection = container.createDiv({ cls: "bk-section" });
    actionsSection.createEl("h3", { text: "\u26A1 Quick Actions" });
    const actionsGrid = actionsSection.createDiv({ cls: "bk-actions-grid" });
    const actions = [
      { icon: "\u2795", label: "Add Product", section: "products" },
      { icon: "\u{1F3AF}", label: "Add Milestone", section: "roadmap" },
      { icon: "\u{1F4B5}", label: "Add Revenue", section: "financial" },
      { icon: "\u{1F4DD}", label: "Edit Executive", section: "executive" }
    ];
    actions.forEach((action) => {
      const btn = actionsGrid.createEl("button", { cls: "bk-action-btn" });
      btn.createEl("span", { text: action.icon, cls: "action-icon" });
      btn.createEl("span", { text: action.label, cls: "action-label" });
      btn.addEventListener("click", () => {
        this.activeSection = action.section;
        this.refresh();
      });
    });
    if (plan.roadmap.milestones.length > 0) {
      const milestonesSection = container.createDiv({ cls: "bk-section" });
      milestonesSection.createEl("h3", { text: "\u{1F5FA}\uFE0F Recent Milestones" });
      const recentMilestones = plan.roadmap.milestones.slice(0, 5);
      const milestonesList = milestonesSection.createDiv({ cls: "bk-milestones-list" });
      recentMilestones.forEach((milestone) => {
        const item = milestonesList.createDiv({ cls: `bk-milestone-item ${milestone.status}` });
        const statusIcon = milestone.status === "completed" ? "\u2705" : milestone.status === "in-progress" ? "\u{1F504}" : milestone.status === "delayed" ? "\u26A0\uFE0F" : "\u{1F4CB}";
        item.createEl("span", { text: statusIcon, cls: "milestone-status" });
        item.createEl("span", { text: milestone.title, cls: "milestone-title" });
        if (milestone.targetDate) {
          item.createEl("span", { text: formatDate(milestone.targetDate), cls: "milestone-date" });
        }
      });
    }
    if (plan.products.length > 0) {
      const productsSection = container.createDiv({ cls: "bk-section" });
      productsSection.createEl("h3", { text: "\u{1F4E6} Products Overview" });
      const productsList = productsSection.createDiv({ cls: "bk-products-overview" });
      plan.products.slice(0, 5).forEach((product) => {
        const item = productsList.createDiv({ cls: "bk-product-item" });
        const categoryIcon = product.category === "wordpress" ? "\u{1F537}" : product.category === "obsidian" ? "\u{1F48E}" : product.category === "service" ? "\u{1F6E0}\uFE0F" : "\u{1F4E6}";
        item.createEl("span", { text: categoryIcon, cls: "product-category" });
        item.createEl("span", { text: product.name, cls: "product-name" });
        item.createEl("span", {
          text: product.status,
          cls: `product-status ${product.status}`
        });
      });
    }
    const footer = container.createDiv({ cls: "bk-dashboard-footer" });
    footer.createEl("span", {
      text: `Last updated: ${formatDate(plan.lastUpdated)}`,
      cls: "bk-last-updated"
    });
  }
  // =========================================
  // EXECUTIVE SUMMARY
  // =========================================
  renderExecutive(container) {
    const plan = this.getActivePlan();
    if (!plan) {
      container.createEl("p", { text: "No plan selected", cls: "bk-no-plan" });
      return;
    }
    const exec = plan.executive;
    const header = container.createDiv({ cls: "bk-section" });
    header.createEl("h2", { text: "\u{1F3AF} Executive Summary" });
    const businessCard = container.createDiv({ cls: "bk-exec-card" });
    businessCard.createEl("h3", { text: "\u{1F3E2} Business Information" });
    const businessInfo = businessCard.createDiv({ cls: "bk-exec-info-grid" });
    this.renderEditableField(businessInfo, "Business Name", exec.businessName, async (value) => {
      plan.executive.businessName = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    });
    this.renderEditableField(businessInfo, "Tagline", exec.tagline, async (value) => {
      plan.executive.tagline = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    }, "A catchy phrase that describes your business");
    this.renderEditableField(businessInfo, "Founder", exec.founder, async (value) => {
      plan.executive.founder = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    });
    this.renderEditableField(businessInfo, "Founded", exec.foundedDate, async (value) => {
      plan.executive.foundedDate = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    }, "e.g., January 2024");
    const missionVisionCard = container.createDiv({ cls: "bk-exec-card" });
    missionVisionCard.createEl("h3", { text: "\u{1F3AF} Mission & Vision" });
    this.renderEditableTextArea(missionVisionCard, "Mission Statement", exec.mission, async (value) => {
      plan.executive.mission = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    }, "What your business does and why it exists");
    this.renderEditableTextArea(missionVisionCard, "Vision Statement", exec.vision, async (value) => {
      plan.executive.vision = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    }, "Where you want your business to be in 5-10 years");
    const valuesCard = container.createDiv({ cls: "bk-exec-card" });
    const valuesHeader = valuesCard.createDiv({ cls: "bk-exec-card-header" });
    valuesHeader.createEl("h3", { text: "\u{1F48E} Core Values" });
    const addValueBtn = valuesHeader.createEl("button", { text: "+ Add Value", cls: "bk-btn-small" });
    addValueBtn.addEventListener("click", () => {
      new EditCoreValueModal(this.app, this.plugin, plan, null, () => this.refresh()).open();
    });
    const valuesContainer = valuesCard.createDiv({ cls: "bk-values-list" });
    if (exec.coreValues.length === 0) {
      valuesContainer.createEl("p", {
        text: 'No core values defined yet. Click "Add Value" to create your first core value.',
        cls: "bk-empty-state-text"
      });
    } else {
      exec.coreValues.forEach((value, index) => {
        const valueItem = valuesContainer.createDiv({ cls: "bk-value-item" });
        const dragHandle = valueItem.createEl("span", { text: "\u2630", cls: "bk-value-drag" });
        dragHandle.title = "Drag to reorder";
        valueItem.createEl("span", { text: value, cls: "bk-value-text" });
        const actions = valueItem.createDiv({ cls: "bk-value-actions" });
        if (index > 0) {
          const upBtn = actions.createEl("button", { text: "\u2191", cls: "bk-btn-icon" });
          upBtn.title = "Move up";
          upBtn.addEventListener("click", async () => {
            const values = [...plan.executive.coreValues];
            [values[index - 1], values[index]] = [values[index], values[index - 1]];
            plan.executive.coreValues = values;
            plan.lastUpdated = new Date().toISOString();
            await this.plugin.saveSettings();
            this.refresh();
          });
        }
        if (index < exec.coreValues.length - 1) {
          const downBtn = actions.createEl("button", { text: "\u2193", cls: "bk-btn-icon" });
          downBtn.title = "Move down";
          downBtn.addEventListener("click", async () => {
            const values = [...plan.executive.coreValues];
            [values[index], values[index + 1]] = [values[index + 1], values[index]];
            plan.executive.coreValues = values;
            plan.lastUpdated = new Date().toISOString();
            await this.plugin.saveSettings();
            this.refresh();
          });
        }
        const editBtn = actions.createEl("button", { text: "\u270F\uFE0F", cls: "bk-btn-icon" });
        editBtn.title = "Edit";
        editBtn.addEventListener("click", () => {
          new EditCoreValueModal(this.app, this.plugin, plan, index, () => this.refresh()).open();
        });
        const deleteBtn = actions.createEl("button", { text: "\u{1F5D1}\uFE0F", cls: "bk-btn-icon bk-btn-danger" });
        deleteBtn.title = "Delete";
        deleteBtn.addEventListener("click", async () => {
          if (confirm(`Delete "${value}"?`)) {
            plan.executive.coreValues.splice(index, 1);
            plan.lastUpdated = new Date().toISOString();
            await this.plugin.saveSettings();
            this.refresh();
            new import_obsidian.Notice("Core value deleted");
          }
        });
      });
    }
    const marketCard = container.createDiv({ cls: "bk-exec-card" });
    marketCard.createEl("h3", { text: "\u{1F3AF} Market & Value" });
    this.renderEditableTextArea(marketCard, "Target Market", exec.targetMarket, async (value) => {
      plan.executive.targetMarket = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    }, "Who are your ideal customers?");
    this.renderEditableTextArea(marketCard, "Unique Value Proposition", exec.uniqueValue, async (value) => {
      plan.executive.uniqueValue = value;
      plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
    }, "What makes your business different from competitors?");
    const previewCard = container.createDiv({ cls: "bk-exec-card bk-exec-preview" });
    previewCard.createEl("h3", { text: "\u{1F4CB} Summary Preview" });
    const previewContent = previewCard.createDiv({ cls: "bk-preview-content" });
    if (exec.businessName) {
      previewContent.createEl("h4", { text: exec.businessName });
    }
    if (exec.tagline) {
      previewContent.createEl("p", { text: exec.tagline, cls: "bk-preview-tagline" });
    }
    if (exec.mission) {
      const missionP = previewContent.createDiv({ cls: "bk-preview-section" });
      missionP.createEl("strong", { text: "Mission: " });
      missionP.createEl("span", { text: exec.mission });
    }
    if (exec.vision) {
      const visionP = previewContent.createDiv({ cls: "bk-preview-section" });
      visionP.createEl("strong", { text: "Vision: " });
      visionP.createEl("span", { text: exec.vision });
    }
    if (exec.coreValues.length > 0) {
      const valuesP = previewContent.createDiv({ cls: "bk-preview-section" });
      valuesP.createEl("strong", { text: "Core Values: " });
      valuesP.createEl("span", { text: exec.coreValues.join(" \u2022 ") });
    }
    const completionScore = this.calculateExecutiveCompletion(exec);
    const completionDiv = container.createDiv({ cls: "bk-completion-indicator" });
    completionDiv.createEl("span", { text: `Section Completion: ${completionScore}%`, cls: "bk-completion-text" });
    const progressBar = completionDiv.createDiv({ cls: "bk-progress-bar" });
    const progressFill = progressBar.createDiv({ cls: "bk-progress-fill" });
    progressFill.style.width = `${completionScore}%`;
  }
  // Helper: Calculate executive summary completion
  calculateExecutiveCompletion(exec) {
    const fields = [
      exec.businessName,
      exec.tagline,
      exec.mission,
      exec.vision,
      exec.founder,
      exec.foundedDate,
      exec.targetMarket,
      exec.uniqueValue,
      exec.coreValues.length > 0
    ];
    const filled = fields.filter((f) => f).length;
    return Math.round(filled / fields.length * 100);
  }
  // Helper: Render editable single-line field
  renderEditableField(container, label, value, onSave, placeholder) {
    const fieldDiv = container.createDiv({ cls: "bk-exec-field" });
    const labelEl = fieldDiv.createEl("label", { text: label, cls: "bk-field-label" });
    const inputWrapper = fieldDiv.createDiv({ cls: "bk-input-wrapper" });
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "bk-field-input",
      value,
      placeholder: placeholder || `Enter ${label.toLowerCase()}...`
    });
    let saveTimeout;
    input.addEventListener("input", () => {
      clearTimeout(saveTimeout);
      saveTimeout = setTimeout(async () => {
        await onSave(input.value);
      }, 500);
    });
    input.addEventListener("blur", async () => {
      clearTimeout(saveTimeout);
      await onSave(input.value);
    });
  }
  // Helper: Render editable textarea field
  renderEditableTextArea(container, label, value, onSave, placeholder) {
    const fieldDiv = container.createDiv({ cls: "bk-exec-field bk-exec-field-textarea" });
    fieldDiv.createEl("label", { text: label, cls: "bk-field-label" });
    const textarea = fieldDiv.createEl("textarea", {
      cls: "bk-field-textarea",
      text: value,
      placeholder: placeholder || `Enter ${label.toLowerCase()}...`
    });
    textarea.rows = 3;
    let saveTimeout;
    textarea.addEventListener("input", () => {
      clearTimeout(saveTimeout);
      saveTimeout = setTimeout(async () => {
        await onSave(textarea.value);
      }, 500);
    });
    textarea.addEventListener("blur", async () => {
      clearTimeout(saveTimeout);
      await onSave(textarea.value);
    });
  }
  // =========================================
  // PRODUCTS (Placeholder)
  // =========================================
  renderProducts(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4E6} Products & Services" });
    section.createEl("p", {
      text: "Coming in Phase 3: Product management, pricing tiers, and bundles.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // MARKET ANALYSIS (Placeholder)
  // =========================================
  renderMarket(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4C8} Market Analysis" });
    section.createEl("p", {
      text: "Coming in Phase 4: Competitors, differentiators, and market insights.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // MARKETING & SALES (Placeholder)
  // =========================================
  renderMarketing(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4E3} Marketing & Sales" });
    section.createEl("p", {
      text: "Coming in Phase 5: Channels, funnel, and pricing strategies.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // OPERATIONS (Placeholder)
  // =========================================
  renderOperations(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u2699\uFE0F Operations" });
    section.createEl("p", {
      text: "Coming in Phase 6: Development, support, and distribution.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // TECHNOLOGY (Placeholder)
  // =========================================
  renderTechnology(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4BB} Technology & Infrastructure" });
    section.createEl("p", {
      text: "Coming in Phase 6: Tech stack, licensing, and analytics.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // FINANCIAL (Placeholder)
  // =========================================
  renderFinancial(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4B0} Financial Plan" });
    section.createEl("p", {
      text: "Coming in Phase 7: Revenue, expenses, and projections.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // LEGAL (Placeholder)
  // =========================================
  renderLegal(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F4DC} Legal & Compliance" });
    section.createEl("p", {
      text: "Coming in Phase 8: Licenses, policies, and EULA.",
      cls: "bk-coming-soon"
    });
  }
  // =========================================
  // ROADMAP (Placeholder)
  // =========================================
  renderRoadmap(container) {
    const section = container.createDiv({ cls: "bk-section" });
    section.createEl("h2", { text: "\u{1F5FA}\uFE0F Milestones & Roadmap" });
    section.createEl("p", {
      text: "Coming in Phase 9: Goals, timeline, and progress tracking.",
      cls: "bk-coming-soon"
    });
  }
};
var QuickCreatePlanModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onComplete) {
    super(app);
    this.planName = "";
    this.template = "blank";
    this.plugin = plugin;
    this.onComplete = onComplete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bkbpm-create-plan-modal");
    contentEl.createEl("h2", { text: "\u{1F4CA} Create New Business Plan" });
    new import_obsidian.Setting(contentEl).setName("Plan name").setDesc("Give your business plan a name").addText(
      (text) => text.setPlaceholder("My Business Plan").onChange((value) => {
        this.planName = value;
      })
    );
    new import_obsidian.Setting(contentEl).setName("Template").setDesc("Start with a template or blank plan").addDropdown(
      (dropdown) => dropdown.addOption("blank", "\u{1F4C4} Blank Plan").addOption("plugin-business", "\u{1F50C} Plugin Business").addOption("saas", "\u2601\uFE0F SaaS Business").addOption("consulting", "\u{1F4BC} Consulting").addOption("nonprofit", "\u2764\uFE0F Non-profit").setValue(this.template).onChange((value) => {
        this.template = value;
      })
    );
    const buttonDiv = contentEl.createDiv({ cls: "bkbpm-modal-buttons" });
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const createBtn = buttonDiv.createEl("button", { text: "Create Plan", cls: "mod-cta" });
    createBtn.onclick = async () => {
      if (!this.planName.trim()) {
        new import_obsidian.Notice("Please enter a plan name");
        return;
      }
      const newPlan = createNewPlan(this.planName.trim(), this.template);
      this.plugin.settings.plans.push(newPlan);
      this.plugin.settings.activePlanId = newPlan.id;
      await this.plugin.saveSettings();
      this.plugin.refreshViews();
      new import_obsidian.Notice(`Created "${newPlan.name}"`);
      this.close();
      this.onComplete();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var EditCoreValueModal = class extends import_obsidian.Modal {
  constructor(app, plugin, plan, valueIndex, onComplete) {
    super(app);
    this.valueText = "";
    this.plugin = plugin;
    this.plan = plan;
    this.valueIndex = valueIndex;
    this.onComplete = onComplete;
    if (valueIndex !== null && plan.executive.coreValues[valueIndex]) {
      this.valueText = plan.executive.coreValues[valueIndex];
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bk-modal");
    const isEdit = this.valueIndex !== null;
    contentEl.createEl("h2", { text: isEdit ? "\u270F\uFE0F Edit Core Value" : "\u2795 Add Core Value" });
    new import_obsidian.Setting(contentEl).setName("Core Value").setDesc("A principle or belief that guides your business").addText(
      (text) => text.setPlaceholder("e.g., Customer First").setValue(this.valueText).onChange((value) => {
        this.valueText = value;
      })
    );
    const suggestionsDiv = contentEl.createDiv({ cls: "bk-value-suggestions" });
    suggestionsDiv.createEl("p", { text: "Suggestions:", cls: "bk-suggestions-label" });
    const suggestions = [
      "Innovation",
      "Integrity",
      "Customer Focus",
      "Quality",
      "Teamwork",
      "Excellence",
      "Sustainability",
      "Transparency",
      "Accountability",
      "Continuous Improvement"
    ];
    const suggestionsGrid = suggestionsDiv.createDiv({ cls: "bk-suggestions-grid" });
    suggestions.forEach((suggestion) => {
      const chip = suggestionsGrid.createEl("button", { text: suggestion, cls: "bk-suggestion-chip" });
      chip.addEventListener("click", () => {
        this.valueText = suggestion;
        const input = contentEl.querySelector("input");
        if (input)
          input.value = suggestion;
      });
    });
    const buttonDiv = contentEl.createDiv({ cls: "bkbpm-modal-buttons" });
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const saveBtn = buttonDiv.createEl("button", {
      text: isEdit ? "Save Changes" : "Add Value",
      cls: "mod-cta"
    });
    saveBtn.onclick = async () => {
      if (!this.valueText.trim()) {
        new import_obsidian.Notice("Please enter a core value");
        return;
      }
      if (isEdit && this.valueIndex !== null) {
        this.plan.executive.coreValues[this.valueIndex] = this.valueText.trim();
        new import_obsidian.Notice("Core value updated");
      } else {
        this.plan.executive.coreValues.push(this.valueText.trim());
        new import_obsidian.Notice("Core value added");
      }
      this.plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
      this.close();
      this.onComplete();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  plans: [],
  activePlanId: "",
  showSidebar: true,
  autoSave: true,
  exportFormat: "json"
};
var BKBusinessPlanSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "\u{1F4CA} Business Plan Manager" });
    containerEl.createEl("p", {
      text: "Manage your business plans and plugin settings.",
      cls: "setting-item-description"
    });
    containerEl.createEl("h2", { text: "\u{1F4CB} Plan Management" });
    const planListContainer = containerEl.createDiv({ cls: "bkbpm-plan-list-container" });
    this.renderPlanList(planListContainer);
    new import_obsidian2.Setting(containerEl).setName("Create new plan").setDesc("Start a new business plan from scratch or from a template").addButton(
      (button) => button.setButtonText("New Plan").setCta().onClick(() => {
        new CreatePlanModal(this.app, this.plugin, () => {
          this.display();
        }).open();
      })
    );
    containerEl.createEl("h2", { text: "\u2699\uFE0F Display Options" });
    new import_obsidian2.Setting(containerEl).setName("Show sidebar on startup").setDesc("Automatically show the business plan sidebar when Obsidian starts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showSidebar).onChange(async (value) => {
        this.plugin.settings.showSidebar = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto-save").setDesc("Automatically save changes as you edit").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSave).onChange(async (value) => {
        this.plugin.settings.autoSave = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u{1F4E4} Export & Import" });
    new import_obsidian2.Setting(containerEl).setName("Export format").setDesc("Choose the format for exporting plans").addDropdown(
      (dropdown) => dropdown.addOption("json", "JSON").addOption("markdown", "Markdown").setValue(this.plugin.settings.exportFormat).onChange(async (value) => {
        this.plugin.settings.exportFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Export all plans").setDesc("Export all your business plans to a file").addButton(
      (button) => button.setButtonText("Export All").onClick(() => {
        this.exportAllPlans();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Import plans").setDesc("Import business plans from a JSON file").addButton(
      (button) => button.setButtonText("Import").onClick(() => {
        this.importPlans();
      })
    );
    containerEl.createEl("h2", { text: "\u26A0\uFE0F Danger Zone" });
    new import_obsidian2.Setting(containerEl).setName("Reset all plans").setDesc("Delete all plans and reset to defaults. This cannot be undone!").addButton(
      (button) => button.setButtonText("Reset All").setWarning().onClick(async () => {
        if (confirm("Are you sure you want to delete ALL plans? This cannot be undone!")) {
          if (confirm("This will permanently delete all your business plans. Continue?")) {
            this.plugin.settings.plans = [];
            this.plugin.settings.activePlanId = "";
            await this.plugin.saveSettings();
            this.plugin.refreshViews();
            new import_obsidian2.Notice("All plans have been reset");
            this.display();
          }
        }
      })
    );
    containerEl.createEl("h2", { text: "\u2139\uFE0F About" });
    const aboutDiv = containerEl.createDiv({ cls: "bkbpm-about" });
    aboutDiv.createEl("p", { text: "BK Business Plan Manager v1.0.0" });
    aboutDiv.createEl("p", { text: "Create and manage comprehensive business plans for your WordPress and Obsidian plugin business." });
    aboutDiv.createEl("p", {
      text: `Total Plans: ${this.plugin.settings.plans.length}`,
      cls: "bkbpm-about-stat"
    });
  }
  renderPlanList(container) {
    container.empty();
    const plans = this.plugin.settings.plans;
    if (plans.length === 0) {
      const emptyDiv = container.createDiv({ cls: "bkbpm-plan-list-empty" });
      emptyDiv.createEl("p", { text: "No business plans yet. Create one to get started!" });
      return;
    }
    for (const plan of plans) {
      const planItem = container.createDiv({ cls: "bkbpm-plan-list-item" });
      if (plan.id === this.plugin.settings.activePlanId) {
        planItem.addClass("is-active");
      }
      const planInfo = planItem.createDiv({ cls: "bkbpm-plan-list-info" });
      planInfo.createSpan({ text: plan.icon, cls: "bkbpm-plan-icon" });
      planInfo.createSpan({ text: plan.name, cls: "bkbpm-plan-name" });
      if (plan.id === this.plugin.settings.activePlanId) {
        planInfo.createSpan({ text: "(Active)", cls: "bkbpm-plan-active-badge" });
      }
      const actionsDiv = planItem.createDiv({ cls: "bkbpm-plan-list-actions" });
      if (plan.id !== this.plugin.settings.activePlanId) {
        const activateBtn = actionsDiv.createEl("button", { text: "Activate" });
        activateBtn.onclick = async () => {
          this.plugin.settings.activePlanId = plan.id;
          await this.plugin.saveSettings();
          this.plugin.refreshViews();
          this.renderPlanList(container);
          new import_obsidian2.Notice(`Switched to "${plan.name}"`);
        };
      }
      const editBtn = actionsDiv.createEl("button", { text: "Edit" });
      editBtn.onclick = () => {
        new EditPlanModal(this.app, this.plugin, plan, () => {
          this.display();
        }).open();
      };
      const deleteBtn = actionsDiv.createEl("button", { text: "\u{1F5D1}\uFE0F", cls: "bkbpm-delete-btn" });
      deleteBtn.onclick = async () => {
        var _a;
        if (confirm(`Delete "${plan.name}"? This cannot be undone.`)) {
          this.plugin.settings.plans = this.plugin.settings.plans.filter((p) => p.id !== plan.id);
          if (this.plugin.settings.activePlanId === plan.id) {
            this.plugin.settings.activePlanId = ((_a = this.plugin.settings.plans[0]) == null ? void 0 : _a.id) || "";
          }
          await this.plugin.saveSettings();
          this.plugin.refreshViews();
          this.renderPlanList(container);
          new import_obsidian2.Notice(`Deleted "${plan.name}"`);
        }
      };
    }
  }
  exportAllPlans() {
    const data = JSON.stringify(this.plugin.settings.plans, null, 2);
    const blob = new Blob([data], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `business-plans-${new Date().toISOString().split("T")[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
    new import_obsidian2.Notice("Plans exported successfully");
  }
  importPlans() {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = ".json";
    input.onchange = async (e) => {
      var _a;
      const file = (_a = e.target.files) == null ? void 0 : _a[0];
      if (!file)
        return;
      try {
        const text = await file.text();
        const plans = JSON.parse(text);
        if (!Array.isArray(plans)) {
          throw new Error("Invalid format");
        }
        for (const plan of plans) {
          const existing = this.plugin.settings.plans.find((p) => p.id === plan.id);
          if (existing) {
            plan.id = plan.id + "-imported";
            plan.name = plan.name + " (Imported)";
          }
          this.plugin.settings.plans.push(plan);
        }
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian2.Notice(`Imported ${plans.length} plan(s)`);
      } catch (err) {
        new import_obsidian2.Notice("Failed to import plans. Invalid file format.");
      }
    };
    input.click();
  }
};
var CreatePlanModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, onComplete) {
    super(app);
    this.planName = "";
    this.template = "blank";
    this.plugin = plugin;
    this.onComplete = onComplete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bkbpm-create-plan-modal");
    contentEl.createEl("h2", { text: "\u{1F4CA} Create New Business Plan" });
    new import_obsidian2.Setting(contentEl).setName("Plan name").setDesc("Give your business plan a name").addText(
      (text) => text.setPlaceholder("My Business Plan").onChange((value) => {
        this.planName = value;
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Template").setDesc("Start with a template or blank plan").addDropdown(
      (dropdown) => dropdown.addOption("blank", "\u{1F4C4} Blank Plan").addOption("plugin-business", "\u{1F50C} Plugin Business").addOption("saas", "\u2601\uFE0F SaaS Business").addOption("consulting", "\u{1F4BC} Consulting").addOption("nonprofit", "\u2764\uFE0F Non-profit").setValue(this.template).onChange((value) => {
        this.template = value;
      })
    );
    const buttonDiv = contentEl.createDiv({ cls: "bkbpm-modal-buttons" });
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const createBtn = buttonDiv.createEl("button", { text: "Create Plan", cls: "mod-cta" });
    createBtn.onclick = async () => {
      if (!this.planName.trim()) {
        new import_obsidian2.Notice("Please enter a plan name");
        return;
      }
      const newPlan = createNewPlan(this.planName.trim(), this.template);
      this.plugin.settings.plans.push(newPlan);
      this.plugin.settings.activePlanId = newPlan.id;
      await this.plugin.saveSettings();
      this.plugin.refreshViews();
      new import_obsidian2.Notice(`Created "${newPlan.name}"`);
      this.close();
      this.onComplete();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var EditPlanModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, plan, onComplete) {
    super(app);
    this.plugin = plugin;
    this.plan = plan;
    this.onComplete = onComplete;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bkbpm-edit-plan-modal");
    contentEl.createEl("h2", { text: "\u270F\uFE0F Edit Plan Details" });
    new import_obsidian2.Setting(contentEl).setName("Plan name").addText(
      (text) => text.setValue(this.plan.name).onChange((value) => {
        this.plan.name = value;
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Description").addTextArea(
      (text) => text.setValue(this.plan.description).onChange((value) => {
        this.plan.description = value;
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Icon").setDesc("Enter an emoji").addText(
      (text) => text.setValue(this.plan.icon).onChange((value) => {
        this.plan.icon = value;
      })
    );
    new import_obsidian2.Setting(contentEl).setName("Color").addColorPicker(
      (color) => color.setValue(this.plan.color).onChange((value) => {
        this.plan.color = value;
      })
    );
    const buttonDiv = contentEl.createDiv({ cls: "bkbpm-modal-buttons" });
    const cancelBtn = buttonDiv.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const saveBtn = buttonDiv.createEl("button", { text: "Save Changes", cls: "mod-cta" });
    saveBtn.onclick = async () => {
      this.plan.lastUpdated = new Date().toISOString();
      await this.plugin.saveSettings();
      this.plugin.refreshViews();
      new import_obsidian2.Notice(`Updated "${this.plan.name}"`);
      this.close();
      this.onComplete();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var BKBusinessPlanPlugin = class extends import_obsidian3.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    console.log("Loading BK Business Plan Manager");
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_BUSINESS_PLAN,
      (leaf) => new BusinessPlanView(leaf, this)
    );
    this.addRibbonIcon("briefcase", "Open Business Plan Manager", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-business-plan",
      name: "Open Business Plan Manager",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "show-dashboard",
      name: "Show Dashboard",
      callback: () => {
        this.activateView("dashboard");
      }
    });
    this.addCommand({
      id: "show-executive",
      name: "Show Executive Summary",
      callback: () => {
        this.activateView("executive");
      }
    });
    this.addCommand({
      id: "show-products",
      name: "Show Products & Services",
      callback: () => {
        this.activateView("products");
      }
    });
    this.addCommand({
      id: "show-financial",
      name: "Show Financial Plan",
      callback: () => {
        this.activateView("financial");
      }
    });
    this.addCommand({
      id: "show-roadmap",
      name: "Show Roadmap & Milestones",
      callback: () => {
        this.activateView("roadmap");
      }
    });
    this.addSettingTab(new BKBusinessPlanSettingTab(this.app, this));
    console.log("BK Business Plan Manager loaded successfully");
  }
  onunload() {
    console.log("Unloading BK Business Plan Manager");
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
    if (!this.settings.plans) {
      this.settings.plans = [];
    }
    if (!this.settings.activePlanId && this.settings.plans.length > 0) {
      this.settings.activePlanId = this.settings.plans[0].id;
    }
  }
  async saveSettings() {
    const activePlan = this.getActivePlan();
    if (activePlan) {
      activePlan.lastUpdated = new Date().toISOString();
    }
    await this.saveData(this.settings);
  }
  getActivePlan() {
    return this.settings.plans.find((p) => p.id === this.settings.activePlanId) || null;
  }
  async activateView(section) {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_BUSINESS_PLAN);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_BUSINESS_PLAN, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      if (section) {
        const view = leaf.view;
        if (view && view.activeSection !== void 0) {
          view.activeSection = section;
          view.refresh();
        }
      }
    }
  }
  refreshViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_BUSINESS_PLAN);
    leaves.forEach((leaf) => {
      const view = leaf.view;
      if (view) {
        view.refresh();
      }
    });
  }
};
